title        : "setlillie.dev"
description  : "setLillie.net"
repo         : "FlameKat53/setlillie.dev"
color        : "#58609a"
markdown_ext : "markdown,mkdown,mkdn,mkd,md,html"
include      : [".well-known"]

defaults:
  - values:
      layout: "default"
      title: "setLillie"

plugins:
  - "jekyll-github-metadata"

sass:
  sass_dir: _sass